#!/usr/bin/env python3

import os
import subprocess
import filecmp

TESTS = [
    "simple",
    "arithmetics/add",
    "arithmetics/add_imm",
    "arithmetics/addc_no_carry",
    "arithmetics/addc_with_carry",
    "arithmetics/addv_no_overflow",
    "arithmetics/addv_with_overflow",
    "arithmetics/cmp_eq",
    "arithmetics/cmp_eq_imm",
    "arithmetics/cmp_ge",
    "arithmetics/cmp_gt",
    "arithmetics/cmp_hi",
    "arithmetics/cmp_hs",
    "arithmetics/cmp_pl",
    "arithmetics/cmp_pz",
    "arithmetics/cmp_str",
    "arithmetics/div0s",
    "arithmetics/div0u",
    "arithmetics/div1_negative",
    "arithmetics/div1_positive",
    "arithmetics/dmulsl",
    "arithmetics/dmulul",
    "arithmetics/dt",
    "arithmetics/extsb",
    "arithmetics/extsw",
    "arithmetics/extub",
    "arithmetics/extuw",
    "arithmetics/macl_accumulation",
    "arithmetics/macl_max_neg",
    "arithmetics/macl_max_pos",
    "arithmetics/macl_neg_x_pos",
    "arithmetics/macl_pos",
    "arithmetics/macw_accumulation",
    "arithmetics/macw_max_neg",
    "arithmetics/macw_max_pos",
    "arithmetics/macw_neg_x_pos",
    "arithmetics/macw_pos",
    "arithmetics/mull",
    "arithmetics/mulsw",
    "arithmetics/muluw",
    "arithmetics/neg",
    "arithmetics/negc_no_borrow",
    "arithmetics/negc_with_borrow",
    "arithmetics/sub",
    "arithmetics/subc_no_underflow",
    "arithmetics/subc_with_underflow",
    "arithmetics/subv_no_underflow",
    "arithmetics/subv_with_underflow",
    "branch/bf",
    "branch/bf_s",
    "branch/bra",
    "branch/braf",
    "branch/bsr",
    "branch/bsrf",
    "branch/bt",
    "branch/bt_s",
    "branch/jmp",
    "branch/jsr",
    "branch/rts",
    "control/clrmac",
    "control/clrt",
    "control/ldc_gbr",
    "control/ldc_sr",
    "control/ldc_vbr",
    "control/ldcl_gbr",
    "control/ldcl_sr",
    "control/ldcl_vbr",
    "control/lds_mach",
    "control/lds_macl",
    "control/lds_pr",
    "control/ldsl_mach",
    "control/ldsl_macl",
    "control/ldsl_pr",
    "control/nop",
    "control/rte",
    "control/sett",
    "control/stc_gbr",
    "control/stc_sr",
    "control/stc_vbr",
    "control/stcl_gbr",
    "control/stcl_sr",
    "control/stcl_vbr",
    "control/sts_mach",
    "control/sts_macl",
    "control/sts_pr",
    "control/stsl_mach",
    "control/stsl_macl",
    "control/stsl_pr",
    "control/trapa",
    "cmt/interrupt_8_32",
    "cmt/interrupt_8_128",
    "cmt/interrupt_8_512",
    "data_transfer/mov",
    "data_transfer/mov_b_load",
    "data_transfer/mov_b_load_0",
    "data_transfer/mov_b_store",
    "data_transfer/mov_b_store_0",
    "data_transfer/mov_bd_load_0",
    "data_transfer/mov_bd_store_0",
    "data_transfer/mov_bg_load_0",
    "data_transfer/mov_bg_store_0",
    "data_transfer/mov_bm_store",
    "data_transfer/mov_bp_load",
    "data_transfer/mov_imm",
    "data_transfer/mov_l_load",
    "data_transfer/mov_l_load_0",
    "data_transfer/mov_l_store",
    "data_transfer/mov_l_store_0",
    "data_transfer/mov_ld_load",
    "data_transfer/mov_ld_store",
    "data_transfer/mov_lg_load_0",
    "data_transfer/mov_lg_store_0",
    "data_transfer/mov_lm_store",
    "data_transfer/mov_lp_load",
    "data_transfer/mov_w_load",
    "data_transfer/mov_w_load_0",
    "data_transfer/mov_w_store",
    "data_transfer/mov_w_store_0",
    "data_transfer/mov_wd_load_0",
    "data_transfer/mov_wd_store_0",
    "data_transfer/mov_wg_load_0",
    "data_transfer/mov_wg_store_0",
    "data_transfer/mov_wm_store",
    "data_transfer/mov_wp_load",
    "data_transfer/movt",
    "data_transfer/swap_b",
    "data_transfer/swap_w",
    "data_transfer/xtrct",
    "exceptions/cpu_address_error",
    "exceptions/fpu_exception",
    "exceptions/illegal_insn",
    "exceptions/illegal_slot",
    "fpu/control/lds_fpscr",
    "fpu/control/lds_fpul",
    "fpu/control/ldsl_fpscr",
    "fpu/control/ldsl_fpul",
    "fpu/control/sts_fpscr",
    "fpu/control/sts_fpul",
    "fpu/control/stsl_fpscr",
    "fpu/control/stsl_fpul",
    "fpu/data_transfer_32bit/fmov",
    "fpu/data_transfer_32bit/fmovs_load",
    "fpu/data_transfer_32bit/fmovs_load_0",
    "fpu/data_transfer_32bit/fmovs_store",
    "fpu/data_transfer_32bit/fmovs_store_0",
    "fpu/data_transfer_32bit/fmovsm_store",
    "fpu/data_transfer_32bit/fmovsp_load",
    "fpu/single_precision/fabs",
    "fpu/single_precision/fadd",
    "fpu/single_precision/fcmp_eq",
    "fpu/single_precision/fcmp_gt",
    "fpu/single_precision/fdiv",
    "fpu/single_precision/fldi0",
    "fpu/single_precision/fldi1",
    "fpu/single_precision/flds",
    "fpu/single_precision/float",
    "fpu/single_precision/fmac",
    "fpu/single_precision/fmul",
    "fpu/single_precision/fneg",
    "fpu/single_precision/fsts",
    "fpu/single_precision/fsub",
    "fpu/single_precision/ftrc",
    "logic_ops/and",
    "logic_ops/and_b",
    "logic_ops/and_imm",
    "logic_ops/not",
    "logic_ops/or",
    "logic_ops/or_b",
    "logic_ops/or_imm",
    "logic_ops/xor",
    "logic_ops/xor_b",
    "logic_ops/xor_imm",
    "logic_ops/tas_b",
    "logic_ops/tst",
    "logic_ops/tst_b",
    "logic_ops/tst_imm",  
    "shifts/rotcl",
    "shifts/rotcr",
    "shifts/rotl",
    "shifts/rotr",
    "shifts/shal",
    "shifts/shar",
    "shifts/shll",
    "shifts/shll2",
    "shifts/shll8",
    "shifts/shll16",
    "shifts/shlr",
    "shifts/shlr2",
    "shifts/shlr8",
    "shifts/shlr16",
]

MSIM_PATH = "../../msim"

DEFAULT_PWD = os.getcwd()

OUTPUT_FILENAME = "out.txt"
EXPECTED_FILENAME = "expected-output.txt"

def run_test(test_folder):
    print("test: {t}".format(t=test_folder).ljust(45, ' '), end="")
    relative_path = os.path.relpath(MSIM_PATH, test_folder)
    try:
        os.chdir(test_folder)
        res = subprocess.run(relative_path, capture_output=True, timeout=10, check=True, text=True)

        # Test didn't use printer, probably because it uses register dumps instead
        # Then use stdout as reference
        if not os.path.exists(OUTPUT_FILENAME):
            with open(OUTPUT_FILENAME, 'w') as f:
                for b in res.stdout:
                    f.write(b)

        assert filecmp.cmp(EXPECTED_FILENAME, OUTPUT_FILENAME), "Files do not match!"
        os.remove(OUTPUT_FILENAME)
    except BaseException  as e:
        print("failure! ({e})".format(e=e))
        exit(-1)

    os.chdir(DEFAULT_PWD)
    print("success")

def main():
    for test in TESTS:
        run_test(test)

if __name__ == "__main__":
    main()
